FROM seedll/ubuntu_python

# runtime dependencies
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    set -eux; \
	apt-get update; \
        apt-get install -y --no-install-recommends \
    	software-properties-common ;\
        apt-add-repository ppa:mutlaqja/ppa -y; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		git \
		indi-full \
		indi-bin \
		gsc \
		kstars-bleeding \ 
		libindi-dev swig \
		libcfitsio-dev \
		libnova-dev \
		; \
	rm -rf /var/lib/apt/lists/*


CMD ["/usr/bin/bash"]