FROM node:14-alpine
ARG INSTALL_PATH=/docker-mcsm
RUN apk --no-cache add git
RUN git clone https://gitee.com/MCSManager/MCSManager-Web-Production $INSTALL_PATH/releases/web
RUN cd $INSTALL_PATH/releases/web && npm i --production --registry=https://registry.npmmirror.com
ENV TZ=Asia/Shanghai
WORKDIR $INSTALL_PATH/releases/web
CMD node app.js